version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo-list-postgres
    environment:
      POSTGRES_DB: todolist_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todolist"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
