export enum ErrorCode {
  // Validation Errors
  VALIDATION_ERROR = "VALIDATION_ERROR",

  // Resource Errors
  TODO_NOT_FOUND = "TODO_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  //   TODO_ALREADY_EXISTS = "TODO_ALREADY_EXISTS",

  // Business Logic Errors
  INVALID_TODO_STATE = "INVALID_TODO_STATE",
  //   TODO_LIMIT_EXCEEDED = "TODO_LIMIT_EXCEEDED",

  // Authentication/Authorization Errors
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",

  // System Errors
  DATABASE_ERROR = "DATABASE_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
