name: CI/CD Pipeline

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Test health endpoint
        run: |
          # Start the server in background
          npm run dev &
          SERVER_PID=$!
          
          # Wait for server to start
          echo "Waiting for server to start..."
          for i in {1..30}; do
            if curl -f http://localhost:3000/health >/dev/null 2>&1; then
              echo "Server is ready!"
              break
            fi
            echo "Attempt $i: Server not ready yet, waiting..."
            sleep 2
          done
          
          # Test the health endpoint
          echo "Testing health endpoint..."
          curl -f http://localhost:3000/health || (echo "Health check failed" && exit 1)
          
          # Clean up
          kill $SERVER_PID
          sleep 2

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security audit
        run: npm audit --audit-level moderate
